version: "3.8"

networks:
  app:
    driver: bridge

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=beer_game
      - POSTGRES_USER=beer_game
      - POSTGRES_PASSWORD=beer_game
    volumes:
      - postgres:/var/lib/postgresql/data 
