// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	BoardID    pgtype.UUID
	Name       string
	State      string
	IsFull     bool
	IsFinished bool
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Order struct {
	OrderID        pgtype.UUID
	Amount         int64
	OriginalAmount int64
	Type           string
	State          string
	SenderID       pgtype.UUID
	ReceiverID     pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Player struct {
	PlayerID    pgtype.UUID
	Name        string
	Role        string
	Stock       int64
	Backlog     int64
	WeeklyOrder int64
	LastOrder   int64
	Cpu         bool
	BoardID     pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
